### ISSUE TITLE
Support Build & Setup Environment Variables

### ISSUE THREAD

**Issue by metaskills** [devcontainers/ci#153]
In my case I have a `postCreateCommand` that clones another organization repo. This works great under Codespaces but is hanging when using this project. I think what I see is that `🏃 start container` will stop here.

```
Cloning into '/workspaces/mysharedrepo'...
Username for 'https://github.com/':
```

And never move from that spot. The lifecycle script is doing something like this.

```
git clone "https://${GITHUB_TOKEN}@github.com/myorg/mysharedrepo.git" /workspaces/mysharedrepo
cd /workspaces/mysharedrepo
```

Any recommendations to get that working?

**Comment by metaskills** [comment]
Would it make sense to have the `env:` variables be accessible to both the build and start stages? That might help here.

**Comment by metaskills** [comment]
FWIW, I would be happy if there was ANY environment variable during the build / start process so I could make some runtime decisions?

**Comment by joshspicer** [comment]
Hey! This proposal makes sense to me.  @stuartleeks I suspect you'll agree this is OK, but curious if there's any thoughts you have counter?

**Comment by stuartleeks** [comment]
I was wondering whether there would be any scenarios where we would want to set the build environment variables independently of the runtime ones.

E.g. would we want to have `buildEnv` and `env`, or just have `env` that is passed to both?

**Comment by Oblynx** [comment]
You can start with passing env to both. Then if an issue is reported with this behavior, we can split it up.

**Comment by metaskills** [comment]
> You can start with passing env to both. Then if an issue is reported with this behavior, we can split it up.

Agreed here too. Thank you.

**Comment by Oblynx** [comment]
Hello! Just bumping this issue, is it being tracked/planned?

**Comment by stuartleeks** [comment]
I've was looking at adding support for this to the action, and was a little confused by the results of my testing for a while so thought I'd drop a comment here.

There's a PR to improve support for this (#211) but depending on how your `devcontainer.json` is set up, you may be able to make this work already.

To do this, you need to have the `remoteEnv` in your `devcontainer.json` referencing a value from `localEnv`:

```jsonc
	 "remoteEnv": {
		"YOUR_ENV" : "${localEnv:YOUR_ENV}"
	}
```

This instructs the devcontainer CLI to set the remote env in the container based on the `localEnv` context.

The `localEnv` context can be set using the `env` property at the step level (i.e. _not_ nested under the `with` block):

```yaml
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.2
        env:
          YOUR_ENV_VAR: some_value
        with:
          runCmd: |
            make the-thing
```

#211 will add update the action so that env vars set in the `env` under the `with` block are passed to the container. This will provide a way to set container env vars without needing to have it set in `devcontainer.json`.

I'll raise an issue to add examples of this to the docs.

**Comment by metaskills** [comment]
I'm trying this out now and still can not figure out how to use an environment variable when the devcontainer is being built. I've read the docs in the PR work @stuartleeks did but still can't figure it out. Is the env only available to runCmd?

**Comment by Oblynx** [comment]
@moleary-gsa what a nice idea! thanks!
